"""
OpenTree Git Package.

Git command building, parsing, and execution.
"""

from opentree.git.commands import (
    cmd_add,
    cmd_branch_list,
    cmd_checkout,
    cmd_checkout_track,
    cmd_cherry_pick,
    cmd_clean,
    cmd_commit,
    cmd_create_tag,
    cmd_delete_branch,
    cmd_delete_tag,
    cmd_diff,
    cmd_fetch,
    cmd_log,
    cmd_merge,
    cmd_new_branch,
    cmd_pull,
    cmd_push,
    cmd_reset,
    cmd_restore,
    cmd_restore_staged,
    cmd_revert,
    cmd_show,
    cmd_stash_apply,
    cmd_stash_drop,
    cmd_stash_list,
    cmd_stash_pop,
    cmd_stash_push,
    cmd_status,
    cmd_tag_list,
)
from opentree.git.parsers import (
    parse_branches,
    parse_log,
    parse_status_v2,
    parse_stash_list,
    parse_tags,
    split_status_by_kind,
)
from opentree.git.runner import GitRunner, SyncGitRunner

__all__ = [
    "cmd_add",
    "cmd_branch_list",
    "cmd_checkout",
    "cmd_checkout_track",
    "cmd_cherry_pick",
    "cmd_clean",
    "cmd_commit",
    "cmd_create_tag",
    "cmd_delete_branch",
    "cmd_delete_tag",
    "cmd_diff",
    "cmd_fetch",
    "cmd_log",
    "cmd_merge",
    "cmd_new_branch",
    "cmd_pull",
    "cmd_push",
    "cmd_reset",
    "cmd_restore",
    "cmd_restore_staged",
    "cmd_revert",
    "cmd_show",
    "cmd_stash_apply",
    "cmd_stash_drop",
    "cmd_stash_list",
    "cmd_stash_pop",
    "cmd_stash_push",
    "cmd_status",
    "cmd_tag_list",
    "parse_branches",
    "parse_log",
    "parse_status_v2",
    "parse_stash_list",
    "parse_tags",
    "split_status_by_kind",
    "GitRunner",
    "SyncGitRunner",
]
